import React from "react";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import headshot from "../public/headshot-transparent.png";
import stock from "../public/stock.png";
import { useState } from "react";

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Andrej Bosanac</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/brand-logo.jpg" />
            </Head>
            <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
                <section className="min-h-screen">
                    <nav className="py-3 mb-3 flex justify-between md:mb-4 md:py-4">
                        <h1 className="text-2xl text-gray-700 dark:text-gray-200 font-medium">
                            Welcome
                        </h1>
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className="cursor-pointer text-2xl text-gray-700 dark:text-gray-200"
                                />
                            </li>
                            <li>
                                <a
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                                    href="https://personal-website123214531.s3.us-west-2.amazonaws.com/Andrej+Bosanac+Resume.pdf"
                                    download
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center">
                        <h2 className="text-5xl py-2 text-teal-600 font-medium">
                            Andrej Bosanac
                        </h2>
                        <h3 className="text-2xl py-2 md:text-3xl text-gray-800 dark:text-gray-200">
                            Software Developer
                        </h3>
                        <p className="text-md py-2 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
                            Welcome to my personal website! Here, you'll find
                            information about me, my background, and my
                            interests. I'm excited to share my experiences and
                            connect with like-minded individuals. Thanks for
                            visiting!
                        </p>
                    </div>
                    <div className="text-5xl flex justify-center gap-8 py-1 text-gray-600 md:py-3 lg:py-3">
                        <a href="https://www.linkedin.com/in/abosanac/">
                            <AiFillLinkedin />
                        </a>
                        <a href="https://github.com/Lebedev225">
                            <AiFillGithub />
                        </a>
                    </div>
                    <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-60 h-60 mt-5 overflow-hidden ">
                        <Image
                            src={headshot}
                            fill
                            style={{ objectFit: "cover" }}
                        />
                    </div>
                </section>
                <section>
                    <div>
                        <h3 className="text-3xl py-1 font-medium text-gray-800 dark:text-teal-600">
                            Portfolio
                        </h3>
                        <p className="text-md py-1 leading-8 text-gray-800 dark:text-gray-200">
                            Below you can find several side projects that I have
                            been working on.
                        </p>
                        <p className="text-md leading-8  text-gray-800 dark:text-gray-200">
                            You can check out the live demo or take a look at
                            the code by clicking one of the buttons below each
                            of the projects.
                        </p>
                    </div>

                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                        <div className="basis-1/3 flex-1">
                            {/* <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                                Machine Learning Data Analyses
                            </p> */}
                            <h3 className="text-3xl pb-4 font-medium text-gray-800 dark:text-teal-600">
                                Machine Learning Data Analyses
                            </h3>
                            <Image
                                src={stock}
                                className="rounded-lg object-cover"
                                width={"100%"}
                                height={"100%"}
                                responsive
                            />
                            {/* buttons for live demo and code */}
                            <div className="text-l flex justify-left py-3 text-gray-600 md:py-3 lg:py-3">
                                <a
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md "
                                    href="https://personal-website123214531.s3.us-west-2.amazonaws.com/Andrej+Bosanac+Resume.pdf"
                                >
                                    Live Demo
                                </a>
                                <a
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-2"
                                    href="https://personal-website123214531.s3.us-west-2.amazonaws.com/Andrej+Bosanac+Resume.pdf"
                                >
                                    Code
                                </a>
                            </div>
                            <div className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                                <ul className="list-disc px-5">
                                    <li>
                                        Developed a Support Vector Machine that
                                        predicts insurance expenses for an
                                        insurance agency
                                    </li>
                                    <li>
                                        Implemented Association Rule Mining
                                        algorithm to discover patterns in
                                        Walmart customers purchases
                                    </li>
                                    <li>
                                        Trained Neural Network model that
                                        predicts whether a person in SF area
                                        rides a train or not with 90% accuracy
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div className="basis-1/3 flex-1">
                            <h3 className="text-3xl pb-4 font-medium text-gray-800 dark:text-teal-600">
                                Online Store
                            </h3>

                            <Image
                                src={stock}
                                className="rounded-lg object-cover"
                                width={"100%"}
                                height={"100%"}
                                responsive
                            />
                            {/* buttons for live demo and code */}
                            <div className="text-l flex justify-left py-3 text-gray-600 md:py-3 lg:py-3">
                                <a
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md "
                                    href="https://personal-website123214531.s3.us-west-2.amazonaws.com/Andrej+Bosanac+Resume.pdf"
                                >
                                    Live Demo
                                </a>
                                <a
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-2"
                                    href="https://personal-website123214531.s3.us-west-2.amazonaws.com/Andrej+Bosanac+Resume.pdf"
                                >
                                    Code
                                </a>
                            </div>
                            <div className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                                <ul className="list-disc px-5">
                                    <li>
                                        Developed a web application using
                                        JavaScript with React as the front-end
                                    </li>
                                    <li>
                                        Implemented user authentication and
                                        integrated Stripe payment processing
                                    </li>
                                    <li>
                                        Created sorting, filtering, and cart
                                        functionalities
                                    </li>
                                    <li>
                                        Deployed web application on AWS cloud
                                        service
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={stock}
                                className="rounded-lg object-cover"
                                width={"100%"}
                                height={"100%"}
                                responsive
                            />
                        </div>
                    </div>
                </section>
            </main>

            <footer className="bg-white text-center dark:bg-gray-900 lg:text-left">
                <div className="p-4 text-center text-gray-800 dark:text-gray-200">
                    © 2023 Andrej Bosanac
                </div>
            </footer>
        </div>
    );
}
