import React from "react";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import headshot from "../public/headshot-transparent.png";
import stock from "../public/stock.png";
import logo from "../public/logo.jpg";
import { useState } from "react";
// import resume from "../public/Andrej-Bosanac-Resume.pdf";

// import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [darkMode, setDarkMode] = useState(false);
    return (
        <div className={darkMode ? "dark" : ""}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
                <section className="min-h-screen">
                    <nav className="py-10 mb-12 flex justify-between">
                        <h1 className="text-xl dark:text-gray-200">
                            Andrej Bosanac
                        </h1>
                        {/* <Image src={logo} className="w-50 h-50" /> */}
                        <ul className="flex items-center">
                            <li>
                                <BsFillMoonStarsFill
                                    onClick={() => setDarkMode(!darkMode)}
                                    className="cursor-pointer text-2xl dark:text-gray-200"
                                />
                            </li>
                            <li>
                                <a
                                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                                    href=""
                                    download
                                >
                                    Resume
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <div className="text-center">
                        <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
                            Andrej Bosanac
                        </h2>
                        <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-200">
                            Software Developer
                        </h3>
                        <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-200">
                            Lorem ipsum dolor sit amet consectetur adipisicing
                            elit. Assumenda, illo atque officia aliquid cum
                            numquam culpa harum tempore mollitia aperiam?
                        </p>
                    </div>
                    <div className="text-5xl flex justify-center gap-8 py-3 text-gray-600">
                        <AiFillLinkedin />
                        <AiFillGithub />
                    </div>
                    <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden ">
                        <Image
                            src={headshot}
                            fill
                            style={{ objectFit: "cover" }}
                        />
                    </div>
                </section>
                <section>
                    <div>
                        <h3 className="text-3xl py-1 dark:text-teal-600">
                            Portfolio
                        </h3>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                            Lorem ipsum dolor sit amet, consectetur adipisicing
                            elit. Accusamus veritatis molestias, explicabo illo
                            aspernatur ducimus dicta totam possimus eligendi
                            voluptatem alias repudiandae voluptate incidunt iste
                            itaque ullam optio facilis quidem, deserunt odio
                            amet libero nemo adipisci! Cum quae repudiandae,
                            soluta voluptate ut reprehenderit, est optio
                            eligendi, iure dolor numquam ex?
                        </p>
                        <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
                            Lorem ipsum, dolor sit amet consectetur adipisicing
                            elit. Quas repellendus harum dolore nobis eveniet
                            recusandae laborum quidem facere beatae rerum.
                        </p>
                    </div>

                    <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={stock}
                                className="rounded-lg object-cover"
                                width={"100%"}
                                height={"100%"}
                                responsive
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={stock}
                                className="rounded-lg object-cover"
                                width={"100%"}
                                height={"100%"}
                                responsive
                            />
                        </div>
                        <div className="basis-1/3 flex-1">
                            <Image
                                src={stock}
                                className="rounded-lg object-cover"
                                width={"100%"}
                                height={"100%"}
                                responsive
                            />
                        </div>
                    </div>
                </section>
            </main>
        </div>
    );
}
